version: '3.9'

services:
  udea-conciliacion:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: udea-conciliacion
    ports:
      - 8000:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      - backend

  mysql-db:
    image: mysql
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=conciliacion
      - MYSQL_USER=conciliacion
      - MYSQL_PASSWORD=conciliacion
    ports:
      - 3306:3306
    networks:
      - backend
          
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mysql-db
    links:
      - mysql-db:db
    networks:
      - backend

networks:
  backend:
    name: backend-network